### ISSUE TITLE
Second day is always missed in logs - why?

### ISSUE THREAD

**Issue by vritme** [ffeast/finam-export#16] opened 2021-01-29 16:05 UTC
Is it just logging imperfection or second day of each month/year/any dataset is always missing in the resulting dataset? @ffeast
![31-30-finam-export](https://user-images.githubusercontent.com/42464402/106298237-7b0bd200-6275-11eb-897e-5393c4105147.jpg)
![31-30-finam-export-2](https://user-images.githubusercontent.com/42464402/106298255-7fd08600-6275-11eb-9620-87d8cdbb4df6.jpg)

**Comment by vritme** [comment] 2021-01-29 16:59
![year](https://user-images.githubusercontent.com/42464402/106304458-2ec49000-627d-11eb-99f8-b9a7faf06d39.jpg)

**Comment by vritme** [comment] 2021-01-29 17:01
![2020-366](https://user-images.githubusercontent.com/42464402/106304685-79460c80-627d-11eb-91d1-56b94f67da6d.jpg)

**Comment by ffeast** [comment] 2021-01-30 16:57
Hi
Need to look into it. Have you checked the actual data in the resulting files? Are any bars missing?

**Comment by vritme** [comment] 2021-01-31 03:57
I see lot's of yearly downloaded files starting from 3-rd of January, but that's may be because of moex work time.

Also i've made some half of the years downloads like BR from 2019.07.01 to 2019.12.31 and in this case there IS 07.02 date, as well as 07.01 and 07.03. So it looks quite indefinite and confusing..

Still, if we look at logs, it tolds  us, that query with day 2 is always missed for no reason. I think it should be more accurate in logging anyway..

**Comment by vritme** [comment] 2021-02-03 14:44
So have you discover something about it?
<img width="415" alt="df2 is missed" src="https://user-images.githubusercontent.com/42464402/106762924-28a52980-6658-11eb-82bb-3f0480a0112d.png">

**Comment by vritme** [comment] 2021-02-04 15:01
Did some more research.
The app in fact missed second day of requested period, which in reality has quotes.
So you can see it on February, but on the next month, March, second day was downloaded successfully. So it looks like unstable behaviour around 2-nd day of period.
Maybe it's only with ticks, but looks like it's some general bug.
<img width="829" alt="day_2_is_missed_ticks" src="https://user-images.githubusercontent.com/42464402/106911250-c6b1f600-6723-11eb-838a-a45ce453f0da.png">
<img width="844" alt="day_2_is_ok_ticks" src="https://user-images.githubusercontent.com/42464402/106911268-c9145000-6723-11eb-9084-44a467c7efc9.png">
<img width="1123" alt="2016-02-02-ok" src="https://user-images.githubusercontent.com/42464402/106911270-c9ace680-6723-11eb-8ddc-a18c418a9e34.png">

**Comment by vritme** [comment] 2021-02-04 15:04
I checked all months of 2016 with working days on 2-nd day of month. Only February has problem, but still, very inconvenient to checks manually gigabytes of txt's...

**Comment by ffeast** [comment] 2021-02-06 16:37
Confirm, there's a bug. Thanks for you report. The cause is slightly different from what you described but it still needs to be fixed

**Comment by ffeast** [comment] 2021-02-06 20:46
Should be fixed in 4.0.2

**Comment by ffeast** [comment] 2021-11-04 10:06
Solved long ago, closing

**Closed by ffeast** 2021-11-04 10:06 UTC
